export const LOAD_PERSISTED_STATE_SUCCESSFUL =
    'LOAD_PERSISTED_STATE_SUCCESSFUL';
export const LOAD_PERSISTED_STATE_FAILED = 'LOAD_PERSISTED_STATE_FAILED';
export const FETCHED_POSTS_SUCCESSFULLY = 'FETCHED_POSTS_SUCCESSFULLY';
export const FETCH_POSTS_FAILED = 'FETCH_POSTS_FAILED';
export const INITIATE_FETCHING_POSTS = 'INITIATE_FETCHING_POSTS'
